require("einenlum.plugins.fugitive")
require("einenlum.plugins.ultisnips")
require("einenlum.plugins.lsp")
require("einenlum.plugins.syntastic")
require("einenlum.plugins.lualine")
require("einenlum.plugins.gps")
require("einenlum.plugins.illuminate")
require("einenlum.plugins.boo")
require("einenlum.plugins.hop")
require("einenlum.plugins.black")
require("einenlum.plugins.gitblame")
-- require("einenlum.plugins.phpactor")
require("einenlum.plugins.projectroot")
require("einenlum.plugins.prettier")
require("einenlum.plugins.fidget")
require("einenlum.plugins.trouble")
