require("einenlum.plugins.fugitive")
require("einenlum.plugins.ultisnips")
require("einenlum.plugins.dap")
require("einenlum.plugins.dbs")
require("einenlum.plugins.lsp")
require("einenlum.plugins.syntastic")
require("einenlum.plugins.fzf")
require("einenlum.plugins.lualine")
require("einenlum.plugins.cmp")
require("einenlum.plugins.illuminate")
require("einenlum.plugins.boo")
require("einenlum.plugins.hop")
-- require("einenlum.plugins.gitblame")
-- require("einenlum.plugins.phpactor")
require("einenlum.plugins.luasnip")
require("einenlum.plugins.projectroot")
require("einenlum.plugins.prettier")
require("einenlum.plugins.fidget")
require("einenlum.plugins.trouble")
require("einenlum.plugins.rust-tools")
require("einenlum.plugins.treesitter")
require("einenlum.plugins.vsnip")
