vim.opt.exrc = true -- Enable local vimrc
vim.opt.hidden = true
vim.opt.wildmenu = true
vim.opt.wildmode="list:longest"
vim.opt.wildignorecase = true -- :e is now case insensitive
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.laststatus=2
vim.opt.backupdir = "~/.config/nvim/backup"
vim.opt.wrap = true
vim.opt.scrolloff=5
vim.opt.title = true
vim.opt.visualbell = true
vim.opt.showmode = true
vim.opt.number = true
vim.opt.expandtab = true
vim.opt.shiftwidth=4
vim.opt.ruler = true
vim.opt.background=dark
vim.g.mapleader = ","
vim.opt.clipboard="unnamedplus" -- Allow to cp/p from clipboard
